version: 1.{build}

image: Visual Studio 2015
platform:
    - x64
    - Win32
configuration: Release

before_build:
    - support\pkgs\win\bin\build_prepare.cmd

build_script:
    - support\pkgs\win\bin\build_run.cmd

after_build:
    - build\build_installer.cmd

artifacts:
    - path: build\Sysmo-Operator-*.exe

deploy:
    release: Sysmo-Operator-$(APPVEYOR_REPO_TAG_NAME)
    description: 'Automatic Sysmo Operator release deployment'
    provider: GitHub
    auth_token:
        secure: JbU57GgB5EBgwKdw4kTc2LTimc85On9dVaiCAbnqIPRbQxEs6KFEBOHxh8eFuqqD
    artifact: /Sysmo-Operator-.*\.exe/
    force_update: true
    draft: true
    prerelease: false
    on:
        branch: master
        appveyor_repo_tag: false

cache:
    - C:\Users\appveyor\SYSMO_OPERATOR_RESSOURCES\
