version: 1.{build}

image: Visual Studio 2015
platform:
    - x64
    - Win32
configuration: Release

before_build:
    - support\pkgs\win\bin\build_prepare.cmd

build_script:
    - support\pkgs\win\bin\build_run.cmd

after_build:
    - support\pkgs\win\bin\build_installer.cmd

artifacts:
    - path: build\*.msi

cache:
  - C:\Users\appveyor\.gradle\
  - C:\Users\appveyor\SYSMO_RESSOURCES\
