version: 1.{build}

clone_folder: c:\projects\SysmoOperator
os: Visual Studio 2013
platform: x64
configuration: Release

before_build:
    - set PATH=C:\Qt\5.5\msvc2013_64\bin;%PATH%
    - echo Running cmake...
    - cd c:\projects\SysmoOperator
    - git submodule update --init --recursive
    - cmake -H. -Bbuild -G "Visual Studio 12 Win64" -DCMAKE_PREFIX_PATH=C:\Qt\5.5\msvc2013_64

build:
    project: build/sysmo-operator.sln

after_build:
    - cd build/
    - cpack
    - .\deps\rrdio\gradlew.bat --stop
    - del C:\Users\appveyor\.gradle\caches\modules-2\modules-2.lock

cache:
  - C:\Users\appveyor\.gradle\caches\
  - C:\Users\appveyor\.gradle\wrapper\
