version: 1.{build}

image: Visual Studio 2015
platform:
    - x64
    - Win32
configuration: Release

before_build:
    - support\packages\win\bin\configure.cmd

build_script:
    - support\packages\win\bin\make.cmd

after_build:
    - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
    - _build\generate_bundle.cmd

artifacts:
    - path: _build\Sysmo-Operator-*.exe
    - path: _build\__installer-*.msi

deploy:
    release: CURRENT
    description: 'Sysmo Operator release'
    provider: GitHub
    auth_token:
        secure: JbU57GgB5EBgwKdw4kTc2LTimc85On9dVaiCAbnqIPRbQxEs6KFEBOHxh8eFuqqD
    artifact: /Sysmo-Operator-.*\.exe/, /__installer-.*\.msi/
    force_update: true
    draft: true
    prerelease: false
    on:
        branch: master
        appveyor_repo_tag: false

cache:
    - C:\Users\appveyor\SYSMO_OPERATOR_RESSOURCES\
