version: 1.{build}
branches:
    only:
        - master
build_script:
    - C:\Qt\5.4\mingw491_32\bin\qmake.exe -set QMAKE_GXX C:\Qt\Tools\ming491_32\g++.exe
    - C:\Qt\5.4\mingw491_32\bin\qmake.exe -config release
    - C:\Qt\Tools\mingw491_32\bin\mingw32-make.exe
