# -*- mode: ruby -*-

ROOT     = Dir.pwd
JAVA_DIR = File.join(ROOT, "rrd4qt")
GRADLE   = File.join(JAVA_DIR, "gradlew")


desc "Build good sized pixmap for tree and side icons"
task :graphics => [:side_icons, :tree_pixmaps]


desc "Build side icons from SVG src"
task :side_icons do
  sh "inkscape -z --export-png=images/dashboard-black.png -w 30 src/dashboard-black.svg"
  sh "inkscape -z --export-png=images/monitor-black.png   -w 30 src/monitor-black.svg"
end



desc "Build tree pixmaps from SVG src"
task :tree_pixmaps do
  pix_size = 26
  pixs = ["hub", "router", "server-generic",
          "wireless-router", "firewall", "printer", "computer-generic",
          "weather-clear-night", "weather-clear", "weather-few-clouds",
          "weather-few-clouds-night", "weather-overcast",
          "weather-severe-alert", "weather-showers-scattered", "weather-showers",
          "weather-snow", "weather-storm", "media-playback-pause",
          "media-playback-start"]
  pixs.each{ |p|
   sh "inkscape -z --export-png=pixmaps/#{p}.png -w #{pix_size} -h #{pix_size} src/#{p}.svg"
  }
end


desc "Build box icons from SVG src"
task :box_icons do
  pix_size = 48
  pixs = ["dialog-warning", "dialog-information", "dialog-error"]
  pixs.each{ |p|
   sh "inkscape -z --export-png=box_icons/#{p}.png -w #{pix_size} -h #{pix_size} src/#{p}.svg"
  }
end


desc "Build std icons from SVG src"
task :std_icons do
  icon_size = 32
  sh "inkscape -z --export-png=icons/hub.png -w #{pix_size} -h #{pix_size} src/hub.svg"
end

task :rpm_icons do
  sizes = ["16", "22", "24", "256", "32", "48"]
  hcolorSrc = "src/sysmo-logo-src.svg"
  hcontrastSrc = "src/sysmo-logo-hc-src.svg"
  FileUtils.cp(hcolorSrc, "../support/packages/rpm/icons/icons/hicolor/scalable/apps/")
  sizes.each{ |s|
    colorPath = "pkgs/rpm_icons/icons/hicolor/#{s}x#{s}/apps"
    contrastPath = "pkgs/rpm_icons/icons/HighContrast/#{s}x#{s}/apps"
    sh "inkscape -z --export-png=#{colorPath}/sysmo.png -w #{s} -h #{s} #{hcolorSrc}"
    sh "inkscape -z --export-png=#{contrastPath}/sysmo.png -w #{s} -h #{s} #{hcontrastSrc}"
  }
end

task :deb_icons do
  sizes = ["128", "64"]
  hcolorSrc = "src/sysmo-logo-src.svg"
  sizes.each{ |s|
    colorPath = "pkgs/deb_icons/#{s}x#{s}"
    sh "inkscape -z --export-png=#{colorPath}/sysmo.png -w #{s} -h #{s} #{hcolorSrc}"
  }
end
