#!/usr/bin/env python2
import sys
import platform

if platform.system() == 'Windows':
    sys.stdout = open("noctopus.stdout.txt", "w")
    sys.stderr = open("noctopus.stderr.txt", "w")

import TkorderMain
TkorderMain.main(sys.argv)
